version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max-old-space-size=4096"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli
      - npm ci

  build:
    commands:
      - ng build --configuration production
    finally:
      - echo "This is the finally block execution!"

artifacts:
  base-directory: dist/code-pipeline-website  # update to your real Angular dist folder
  files:
    - '**/*'

